### ISSUE TITLE
enclosure STL designs

### ISSUE THREAD

**Issue by swiftraccoon** [islandmagic/bb-link#1]
![image](https://github.com/islandmagic/bb-link/assets/47705353/312f6a15-d332-4509-ab37-51d164e1ff15)

Note the size in mm.

commit 33436c0

**Comment by georges** [comment]
The enclosure that also double as a swimming pool.

I'm not seeing that. Did you make sure your user preferences are set to mm?

<img width="744" alt="Screenshot 2024-02-06 at 11 38 52 AM" src="https://github.com/islandmagic/bb-link/assets/3819/f06b2212-2107-4844-a4e6-8b3998d4cff4">

**Comment by swiftraccoon** [comment]
Yeah, the settings were correct.

I see the problem now, however. You cannot right click "Save Link As". You must go the file in GitHub directly and then click the "Download Raw File" button (when you haven't checked out the repo locally, that is). My apologies!
