### ISSUE TITLE
TH-D75E doesn't transmit

### ISSUE THREAD

**Issue by F4LFJ** [islandmagic/bb-link#10]
Hello,

I've used the components described in this repository and have compiled the latest ino file.
On my phone the firmware version is described as v0.7.4

Radiomail/BB-link would switch the HT to the selected frequency and Kiss mode but the TH-D75 is not transmitting. 
I can see the led on the Tinypico board blinking red but no tranmission on the HT.

Once the transmission request cancelled, BB-link restore the original frequency and mode.

TH-D75E
Tinypico USB-C
iPhone 11, iOS 17.3.1
Radiomail 1.3.1 (7)
BB-link 1.0.1 (2), firmware 0.7.4

73,
Claude, F4LFJ

**Comment by georges** [comment]
If the adapter connects to the radio but the radio does not transmit, check the TNC settings.
Go to Menu > Configuration > Interface > KISS (983) and set it to Bluetooth.

**Comment by F4LFJ** [comment]
Thanks, it was that!
All working know...just have to find a station that I can work with.

By the way, I made a case that can be mounted at the place of the belt clip. 
I can share the STL files.

<img width="1000" alt="image" src="https://github.com/islandmagic/bb-link/assets/162371197/887115a8-2838-4ce4-be69-77f5eaeca766">
<img width="1000" alt="image" src="https://github.com/islandmagic/bb-link/assets/162371197/9e9bde79-2eca-4354-8030-9330593279dd">
<img width="750" alt="image" src="https://github.com/islandmagic/bb-link/assets/162371197/ab22960c-eab1-4896-a311-b57787b00de0">
<img width="1000" alt="image" src="https://github.com/islandmagic/bb-link/assets/162371197/33f3c67f-4d20-4b9b-9c1c-9a0b7d872651">

![image](https://github.com/islandmagic/bb-link/assets/162371197/377148f9-881d-465a-b98a-fc4651dd2efa)
![image](https://github.com/islandmagic/bb-link/assets/162371197/25271158-2c6b-4f21-93cb-821c6007fbca)
![image](https://github.com/islandmagic/bb-link/assets/162371197/aecae9b2-5760-44c9-a3aa-b9e56150fae7)
![image](https://github.com/islandmagic/bb-link/assets/162371197/de08b0f9-ac8c-4cd1-9a4d-882382070a85)

**Comment by georges** [comment]
Great to hear you're up and running. Fantastic job on the case. I had originally thought of going vertical, but clearly lack the skills to make it be as streamline as your design. 

Do you mind sending a pull request with the .stl files in the enclosure directory and I'll be more than happy to merge this in.

**Comment by F4LFJ** [comment]
Great you like the case!
No sure how to pull a request to add stl files only, so you should have received a email at your winlink address that contain a link to a dropbox folder.

Regards,
Claude

**Comment by georges** [comment]
Link did not seem to have gone thru. Can you post it here? Thanks. On Mar 10, 2024, at 03:10, F4LFJ ***@***.***> wrote:﻿
Great you like the case!
No sure how to pull a request to add stl files only, so you should have received a email at your winlink address that contain a link to a dropbox folder.
Regards,
Claude

**Comment by F4LFJ** [comment]
Ok,this link should work:
https://www.dropbox.com/scl/fo/olg7sb9cd9zcofyi6ggig/h?rlkey=3vxm2wyfdxv4gsjwn9tiy6y8t&dl=0

**Comment by georges** [comment]
Perfect. I've updated the repo with your files. I'm going to have to print one of those, they look cool. Merci Claude!

**Comment by F4LFJ** [comment]
De rien! Eventuellement je peux t'envoyer une paire de ses boitiers.
