### ISSUE TITLE
Feature Request: Output TX/RX Pakets via serial console

### ISSUE THREAD

**Issue by 9V1LH** [islandmagic/bb-link#11]
Aloha from Singapore!

For debugging purposes, it would be beneficial if the received and transmitted packets were sent to the serial output.

73 & 55 de Stephan 9V1LH / DG1BGS

**Comment by georges** [comment]
What format would you expect the packet to be in? KISS frames in hex format?

**Comment by 9V1LH** [comment]
In the best case it would show the packets in a readable format like the raw packets you would see in the aprs.fi app

**Comment by georges** [comment]
That would require needing to decode AX.25 protocol to interpret the payload. Fun, but maybe overkill for this adapter. What would you expect to get that you can't get in aprs.fi?

**Comment by 9V1LH** [comment]
I agree. I had another idea and for this, I would also need to decode the AX.25 protokoll. However, I wasn't paying too much attention and thought that the radio already sent the KISS packets which could be easily been written to the serial output. Maybe I take a closer look at it when I have some spare time.
