### ISSUE TITLE
Feature Request: Convert Raw-Pakets to KISS-Pakets

### ISSUE THREAD

**Issue by 9V1LH** [islandmagic/bb-link#12]
Aloha from Singapore!

I have another use case where I want the TH-D74 to remain in APRS standalone mode. However, in this mode, you can still output the raw packets via Bluetooth. It would be great if we could convert them into KISS packets and send them to the aprs.fi iOS app to continue displaying the received stations on the map.

73 & 55 de Stephan 9V1LH / DG1BGS

**Comment by georges** [comment]
Interesting idea. I'll have to research this some more. However right now, when a device connects to B.B. Link via BLE, it automatically puts the radio in KISS mode because presumably a client is wanting to talk to the TNC. There would need some extra logic to make this conditional.
