### ISSUE TITLE
feature request: M5StickC Plus support

### ISSUE THREAD

**Issue by fanlessfan** [islandmagic/bb-link#13]
Hello,

Could we add support for M5StickC Plus (ESP32-PICO-D4, with battery, buttons,screen,etc and case)?

https://shop.m5stack.com/products/m5stickc-plus-esp32-pico-mini-iot-development-kit

thx
VA3EMQ

**Comment by fanlessfan** [comment]
or add support for Atom Lite (Infra-Red LED, RGB LED, buttons) and Atom Matrix
https://shop.m5stack.com/products/atom-lite-esp32-development-kit
https://shop.m5stack.com/products/atom-matrix-esp32-development-kit

**Comment by georges** [comment]
The M5StickC looks like an interesting all in one device. I don't have access to any of these devices, but if someone wants to open a pull request with proper support, I'll be happy to review.

**Comment by fanlessfan** [comment]
Is there anyone can update the code to add the support for M5StickC Plus? Here is the schematic [https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/schematic/Core/M5StickC_Plus/StickC_Plus_20200616.pdf](url)

**Comment by fanlessfan** [comment]
the atom lite is smaller and have all the requirements for BB-Link. we don't need battery as we can plug it in the iPad or iPhone directly. And it only costs $7.5.
https://shop.m5stack.com/products/atom-lite-esp32-development-kit
