### ISSUE TITLE
TinyPICO board sleeping even when USB-C powered

### ISSUE THREAD

**Issue by ftmiranda** [islandmagic/bb-link#16]
Hello, 
I followed this YouTube video https://www.youtube.com/watch?v=xLze6qDOLww&t=1127s and the solution proposed works extremely well.
Since I did not want to bother with the internal battery, I decided just to power the board with the USB-C. All works well, until you power off your D75, close the RadioMail on your iPhone and you keep the TinyPICO board powered by a large PowerBank... after a while, the board will enter in some sort of sleep mode. If I power back on my D75, and open the RadioMail, try to connect using packet.... nothing... the connection times out. If I unplug the USB-C and plug it again, after a few seconds I can re-check my email using RadioMail and all works great again. 
Is there any way to prevent the board from sleeping at all when powered by the USB-C? Thank you

**Comment by georges** [comment]
Can you plug the TinyPICO into a computer instead of power bank and open the serial console (easiest is to open in ArduinoIDE). After a while, you should see something like:

```
I: Idle for 300 s
I: On USB power, stay awake
```

**Comment by ftmiranda** [comment]
Something I  noticed, I had a firmware update today, 0.74-> 0.75 
After this update, I left the board connected to a power bank for hours, then I turned on my D75, after 5 seconds it connected to the pico board, and RadioMail just worked. Not sure if the firmware update did the trick or if I had a glitch before, but now it seems to work just fine!! Thank you
