### ISSUE TITLE
Constantly losing BLE connection 

### ISSUE THREAD

**Issue by 2e0wkw** [islandmagic/bb-link#18]
In the B.B.Link app as soon as i move away from the page that shows the paired device the app reports that it has lost BLE connection. I am sure it hasn't.

E.G i connect my iPhone and TH-D75 and go to aprs.fi to send a message when i return to B.B.Link app it reports that it has lost the BLE connection

Setup:
TinyPico with latest firmware built via Arduini IDE 2.3.2 and esp32 2.0.11
TH-D75
iPhone 14 Pro with IOS 17.4.1

**Comment by georges** [comment]
It's by design. With BLE, there can only be one application connected. The B.B. Link configurator app is meant to only be run seldomly to setup pairing with a radio. When the app looses focus, it automatically disconnects so that another app (APRS.fi in your case) can connect.
