### ISSUE TITLE
Tinypico discontinued

### ISSUE THREAD

**Issue by hemna** [islandmagic/bb-link#22]
Is there another board that this will work on?  the TinyPico is now discontinued and hard to find.

Thanks

**Comment by Beavxx** [comment]
Mouser still has some left.

**Comment by georges** [comment]
Not sure where you've seen that it's discontinued. Plenty of inventory from the maker: https://unexpectedmaker.com/shop.html#!/TinyPICO/p/577111313

Alternatively, you can buy a ready made version I created: https://getbblink.com
