### ISSUE TITLE
TinyPICO TP01 USB C

### ISSUE THREAD

**Issue by Thuff256** [islandmagic/bb-link#7]
I flashed my TinyPICO with the Mac version of the Arduino IDE 2.3.3 and I got what looked like it downloaded to work. 

Leaving...
Hard resetting via RTS pin...

Unfortunately, the amber LED never came on indicating the TinyPICO reset and rebooted.  When I removed the USBC cable and reapplied it would not come out of the state it was stuck in.  I tried two more times to flash the board with no change.  

It did say Installed ArduinoQueue: 1.2.5 
FreeRTOS:11.0.1-5
TinyPICO Helper Library:1.4.0
esp32.2.0.14

I am sure I missed something so please let me know what I can do to get this working.  

If you need anything else please let me know to get this working.   

Tim KM4ESU

**Comment by Thuff256** [comment]
I missed the ArduinoLog so I added it and flashed the board.  I check the serial Monitor and this is what I saw. 
����������������������������������������������������������������������������������������������
I am set a 115200 Baud.

**Comment by georges** [comment]
Yes the board should come up at 115200 baud. If you're seeing gibberish it means that the speed is not setup properly, perhaps the code is not starting. Try to change the serial monitor speed down to 9600 baud. Press reset on the board and see if you get some output. It should show you what's happening on the board, either the default program running, or something else.

Also, please include the complete output of the flashing window just in case something is not working correctly during that phase.

**Comment by Thuff256** [comment]
Reset got the serial to work at 115200.  Please let me know what to do next.

Thank you!
Tim 

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0

**Comment by georges** [comment]
This is what you should see on a properly flashed TinyPICO

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0

 ___   ___     _    _      _
| _ ) | _ )   | |  (_)_ _ | |__
| _ \_| _ \_  | |__| | ' \| / /
|___(_)___(_) |____|_|_||_|_\_\

Booting up B.B. Link v0.7.4 on TinyPICO v3.0

Heap free: 232100, usage: 11 %
Flash size: 1190704, total: 1310720, usage: 90 %
Log level: INFO
```

It appears that your board is not executing the setup() properly for some reason. Maybe it's defective? Have you tried flashing as simple hello world and see if it works?

**Comment by Thuff256** [comment]
I tried two different boards with the same result. They came from the Unexpected Maker in Australia. I practiced good ESD too. I guess I can order 2 more to see but the lights come on and its not dead.

**Comment by georges** [comment]
Mmm, I'd say it's probably something else. When you say the lights come on, are you talking about the top left blue and the top right blinking yellow?

![IMG_6295](https://github.com/islandmagic/bb-link/assets/3819/90110675-8cac-4151-a5cf-adb13fab6006)

And from what you said earlier, the tri-color on the bottom is not coming on for you?

**Comment by georges** [comment]
And just to confirm, when you flashed you selected TinyPICO and the wchusbserial port?
<img width="657" alt="Screenshot 2024-02-25 at 1 45 08 PM" src="https://github.com/islandmagic/bb-link/assets/3819/01b9bcae-d01f-4004-8682-bf4172d7acfa">

**Comment by Thuff256** [comment]
Yes, the bottom blue and amber come on but the tri-color does not.  This is the same on the board you show.  I do have an earlier USB-C as well but until I know these two are dead I will wait in it.  The computer is an M1 Mac with an Apple USBC Thunderbolt data cable to program the board.

**Comment by georges** [comment]
Can you try to remove that line

https://github.com/islandmagic/bb-link/blob/51684739e3f17b9a8a742f20d39347f30b24f7e4/src/bb-link/bb-link.ino#L24

and reflash?

**Comment by Thuff256** [comment]
Yes, that is the board and port note the amber LED by the USB-C connector is blinking and the blue is on.

**Comment by Thuff256** [comment]
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,

**Comment by Thuff256** [comment]
Yes I think so 

Where do I find the code to make this change?

**Comment by georges** [comment]
In your Arduino IDE, find the file named `bb-link.ino` and scroll to line 24

**Comment by Thuff256** [comment]
I tried to edit line 24 but the code is read-only.  I am not sure if I can pull it into an editor and edit then past the whole thing into the Arduino IDE.  

Tim

**Comment by Thuff256** [comment]
I believe I removed LIne 24 and sent it to the IDE. I am not positive since I am not a get-hub expert.  I did not see any change. 

Do you have any other changes you can suggest to get this working

Tim

**Comment by Thuff256** [comment]
I did test the third board all USB-C but that one is older none seem to work.  I am not sure what I am doing wrong but I do hope to get them working.  I have 2 D74 that need this one for traveling the other home.  

I hope we can find out why they do not work.  

Tim

**Comment by georges** [comment]
There should not be anything involving GitHub, you just need to edit your local file from within the Arduino IDE.

**Comment by Thuff256** [comment]
This may be the problem I can't find the local file?  it should be in /Users/timhuffaker/Documnets/Aruino I do see the libraries but not the sketch file.  Is it hidden?

**Comment by georges** [comment]
The ArduinoIDE should have tabs open with files. 

<img width="1408" alt="Screenshot 2024-02-25 at 4 07 16 PM" src="https://github.com/islandmagic/bb-link/assets/3819/0ebb29ac-a174-4922-881a-9e123401a7ef">

If bb-link.ino does not show, use the 3-dot menu to open it.

<img width="389" alt="Screenshot 2024-02-25 at 4 08 26 PM" src="https://github.com/islandmagic/bb-link/assets/3819/ab85ab15-62a4-4f7d-84a7-31f426b356a1">

**Comment by Thuff256** [comment]
Well, I found the problem your GetHub file is not loading in the download and there is nothing in the three dots.  I did follow your youtube and copied the file but I do not know why the file is not loaded.  Should I click the raw button and copy the file?   This is what I do for Raspberry Pi's to download code.

**Comment by georges** [comment]
<img width="679" alt="Screenshot 2024-02-25 at 4 41 32 PM" src="https://github.com/islandmagic/bb-link/assets/3819/8e0f1111-c684-4079-b0be-368b54251070">

1. On GitHub, click green button, select download zip.
2. Expand the zip in your local directory
3. Double click `bb-link.ino` in `bb-link-master/src/bb-link` folder
4. Arduino IDE should open an load all the files for you

You probably flashed an empty file to the board, so try to flash these file first before trying to remove the line I had suggested.

**Comment by Thuff256** [comment]
Success I have an amber LED.  Not to continue testing and add the battery.  For you and some humor, my son came in and I asked him for help.  He did what you showed before you showed it and that got it working.  Then I read your post and LOL. 

Thank you for your help!
Tim
