### ISSUE TITLE
Compilation error: ArduinoLog.h: No such file or directory

### ISSUE THREAD

**Issue by F4LFJ** [islandmagic/bb-link#8]
Hi Georges,

Not an issue anymore but here is what I have encountered at the first compilation:
 
During the first compilation I've got the following error:
Compilation error: ArduinoLog.h: No such file or directory

Line 15 of the ino file reference it: #include <ArduinoLog.h>

The installation of the ArduinoLog library is not mentioned in your video.
So I've installed the v1.1.1 by Thijs Elenbaas

I was able to compile and upload the file to the board.
The BB-link apps see the board, it works!
I just wait few days to receive my Th-D75.

Thanks for this great job!

73, Claude, F4LFJ

**Comment by georges** [comment]
Thanks Claude. Yes the logging has been added since the video. The README has been updated so always a good idea to check that too. Glad you got it running.

**Comment by F4LFJ** [comment]
Great! Thanks for the feedback George!
