### ISSUE TITLE
Radio Control Change Frequency

### ISSUE THREAD

**Issue by giminok** [islandmagic/bb-link#9]
I had firmware 0.7.3 installed and radiomail would put into kiss mode and change the frequency.  When finished it would restore the old frequency and then turn off kiss mode.

I upgraded firmware to 0.7.4 using bblink app.  Now it will put into kiss mode, but does not change the frequency on the radio.

Tried with vfo a and b.  I have reset the bblink 2x and repaired to the radio and iphone.  Still will not change the frequency.

Do not see an option to downgrade firmware to 0.7.3 to retest.

When I manually change the frequency on the radio, the radio/radiomail will send the message.

iphone 15 pro max, IOS 17.3.1
B.B.link 1.0.1 (2)
Radiomail 1.3.1 (7)
Kenwood Th-D75a radio

![IMG_1465](https://github.com/islandmagic/bb-link/assets/25875291/aa94f166-d9ca-4260-9377-5d8fe2002e8b)

**Comment by georges** [comment]
Can you try to upgrade to 0.7.5 and see if you're still experiencing this problem?

**Comment by giminok** [comment]
@georges I tried 0.7.5 and it is now working for me.  thx
